test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

railway:
  service: S3
  endpoint: <%= ENV.fetch("ENDPOINT", "") %>
  access_key_id: <%= ENV.fetch("ACCESS_KEY_ID", "") %>
  secret_access_key: <%= ENV.fetch("SECRET_ACCESS_KEY", "") %>
  region: <%= ENV.fetch("REGION", "") %>
  bucket: <%= ENV.fetch("BUCKET", "") %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
